### PR TITLE
 Add "const" attribute to string parameter of sarrayAddString and remove unneeded type casts

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by DanBloomberg** [comment]
Did you change the prototype in allheaders.h?

**Comment by DanBloomberg** [comment]
sarrayAddString() can take the parameter L_INSERT, which puts the string directly into the sarray.  You wouldn't do that for a string  that is initialized to a const char value, such as:
    const char  *str = "this is a string";
But you could do it for a string that has been made on the heap, and needs to be free'd.

For such a heap-based string, could we possibly run into problems when later on the array of strings is destroyed?

**Comment by stweil** [comment]
> Did you change the prototype in allheaders.h?

Yes, see [here](https://github.com/DanBloomberg/leptonica/pull/352/files#diff-6afe82e0a13c1756c25f60b60211de8c).

**Comment by stweil** [comment]
> For such a heap-based string, could we possibly run into problems when later on the array of strings is destroyed?

The change here does not change the way how `sarrayAddString` works. It is still possible to add a constant string with `L_INSERT` which will result in an error when the array is destroyed. `L_INSERT` will work only for strings which were allocated on the heap and not free'd anywhere else.

**Comment by DanBloomberg** [comment]
Yes, this is fine.  Thank you for getting rid of those ugly casts.

**Pull request merged**
