### PR TITLE
Prepare new bug fix release 1.83.1

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
I hope I did not miss anything. After merging the pull request, the tag 1.83.1 can be added and 1.83.1 can be released.

**Comment by DanBloomberg** [comment]
Thank you for doing this, Stefan !!!

**Comment by DanBloomberg** [comment]
Looking again, I think you missed the patch number in:
      CMakeLists, allheaders.h and allheaders_top.h, and makefile.static.
Sorry I didn't notice immediately.

**Comment by DanBloomberg** [comment]
My checklist for new release versioning is:

        src/allheaders.h:  new minor version number (e.g. 83)
        src/allheaders_top.txt:  new minor version number (e.g., 83)
        src/makefile.static: new MINOR_REV (e.g., 83) or PATCH_REV (e.g., 0)
        src/Makefile.am: set SO number in liblept_la_LDFLAGS (e.g., 6:0:0)
        CMakeLists.txt: set VERSION_* to correct values
        src/CMakeLists.txt:  set PROPERTIES VERSION (e.g., 6.0.0)
                                       and PROPERTIES SOVERSION (e.g, 6)
        configure.ac: has the new version number (e.g., 1.83.0)
        Doxyfile: has new version number (e.g., 1.83.0)
        sw.cpp: has the new version number (e.g., 1.83.0)

Total of 9 files (!)

**Pull request merged**
