### PR TITLE
Fix memory leak in pageseg_reg

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by DanBloomberg** [comment]
Thanks.  Was that found by coverity scan?

**Comment by stweil** [comment]
No, only indirectly. I had run `pageseg_reg` to examine a leak which was reported by coverity scan and detected this one.

**Comment by amitdo** [comment]
Dan, Stefan,

How about adding a workflow that uses clang sanitizers with all Leptonica's programs? You can set it to run daily or weekly.

**Comment by DanBloomberg** [comment]
That might be too much for me to deal with, even assuming it is possible somehow to turn 300 programs into sanitizers.  One thing we learned about sanitizers is that you don't want to test existing I/O libraries with it (it finds stuff you can't deal with), so for functions that need an image (most do), you need to use a simple encoding scheme -- Adam Korczynski and I settled on spix (un-encoded raster image) for payloads.

**Comment by stweil** [comment]
A first result of a local test with sanitizer flags shows indeed many issues (mainly from graphic libraries), but also detected the issue which I fixed in pull request #652.

**Comment by stweil** [comment]
The address sanitizer deteced some more issues. I added fixes for those to #652 now.

**Comment by amitdo** [comment]
Stefan,

Another thing you can run on Leptonica's codebase is clang-tidy (it also have all the default checkers included by scan-build).

**Pull request merged**
