### PR TITLE
add missing openjpeg libs to lept.pc

### LINKED ISSUE #386: Missing openjpeg in .pc file
Static linking fails because `liblept.a` depends on openjpeg but this is missing from the pkg-config info:
https://github.com/DanBloomberg/leptonica/blob/ed2d7c6370bbeea2d2f843392b62239560566528/lept.pc.in#L10

### PR DESCRIPTION
**Pull request by jeroen**
fixes #386

### CODE REVIEW

**Comment by zdenop** [comment]
@DanBloomberg : this PR has no direct impact on build - it just provided information for pkg_config, how leptonica was linked...

Anyway here is output from windows (cmake&clang build):
```
f:\Project-Personal\clang_shared\leptonica\prog>..\build.clang\bin\jp2kio_reg.exe generate

////////////////////////////////////////////////
////////////////   jp2kio_reg   ///////////////
////////////////////////////////////////////////
leptonica-1.79.0 (Apr  8 2019, 16:01:47) [MSC v.1915 LIB Release x64] : libgif 5.1.2 : libjpeg 6b (libjpeg-turbo 2.0.2) : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.0
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Info in fopenReadFromMemory: work-around: writing to a temp file
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Info in fopenReadFromMemory: work-around: writing to a temp file
Warning in fgetJp2kResolution: image resolution not found
Info in fopenReadFromMemory: work-around: writing to a temp file
Warning in fgetJp2kResolution: image resolution not found
Time:   1.141 sec

f:\Project-Personal\clang_shared\leptonica\prog>..\build.clang\bin\jp2kio_reg.exe compare

////////////////////////////////////////////////
////////////////   jp2kio_reg   ///////////////
////////////////////////////////////////////////
leptonica-1.79.0 (Apr  8 2019, 16:01:47) [MSC v.1915 LIB Release x64] : libgif 5.1.2 : libjpeg 6b (libjpeg-turbo 2.0.2) : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.0
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Info in fopenReadFromMemory: work-around: writing to a temp file
Warning in fgetJp2kResolution: image resolution not found
Warning in fgetJp2kResolution: image resolution not found
Info in fopenReadFromMemory: work-around: writing to a temp file
Warning in fgetJp2kResolution: image resolution not found
Info in fopenReadFromMemory: work-around: writing to a temp file
Warning in fgetJp2kResolution: image resolution not found
Time:   1.063 sec
```

**Comment by zdenop** [comment]
@DanBloomberg : do you need some more info to this PR?

**Comment by DanBloomberg** [comment]
Sorry for the delay.  In the interim, we added LIBWEBPMUX to the set of libs.

Perhaps someone can resolve the conflict (I don't know how), build and then we can merge the PR.

**Comment by zdenop** [comment]
I do not have write access, so I send the new PR.

**Pull request closed without merging**
