### PR TITLE
Added fuzzers, rewrote an existing fuzzer

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR rewrites the blend_fuzzer and adds new fuzzers.

Furthermore compilation for seed corpus for the fuzzers has been added.

### CODE REVIEW

**Comment by DanBloomberg** [comment]
Hi Adam -- sorry for the delay.  I hope to be able to review this and get it installed by tomorrow, Friday the 23rd.

**Comment by AdamKorcz** [comment]
No problem at all! Take all the time you need!

**Review by DanBloomberg — CHANGES_REQUESTED** [review]
in adaptmap_fuzzer.cc, pixContrastNorm() returns a pix.

in blend_fuzzer.cc, pixBlendBackgroundToColor() should have pix_copy for the first 2 args; don't need pix1

     ditto for pixBlendColorByChannel(),
         replace pix1 byy pix_copy.  The first 2 args must be the same if the first arg is not NULL

      ditto for pixBlendGrayAdapt()
      ditto for pixBlendGrayInverse()
      ditto for pixBlendHardLighl()
     ditto for pixMultiplyByColor()

In classapp_fuzzer.cc, pixFindWordAndCharacterBoxes():
    you have already made a boxa1.  The ptr will be nulled by the function, causing a memory leak

**Comment by DanBloomberg** [comment]
Thank you, Adam.  Don't worry about the mac build failure -- it has been failing for a couple of weeks at least, and Egor knows about it.

**Comment by AdamKorcz** [comment]
Awesome. Thanks for letting me know.

**Pull request merged**
