### PR TITLE
TiffIO errors print state of relevant check failed for easier debugging

### PR DESCRIPTION
**Pull request by l1n**

### CODE REVIEW

**Comment by zdenop** [comment]
This PR is here quite a long time...

**Comment by l1n** [comment]
Can someone rerequest tests? I can try and bring it up to date.

**Comment by DanBloomberg** [comment]
I'm very sorry -- somehow this slipped by last year (maybe covid, or the fact that it failed tests?)
It's a reasonable PR and should have been dealt with.

@l1n  Do you want to update and test?

**Comment by l1n** [comment]
I'm not sure how to rerequest tests unfortunately, but I'd be happy to update it if someone explains that!

**Comment by DanBloomberg** [comment]
I'm very sorry -- somehow this slipped by last year (maybe covid, or the fact that it failed tests?)
It's a reasonable PR and should have been dealt with.

@l1n  Do you want to update and test?

**Comment by DanBloomberg** [comment]
I've made these changes by hand.  Am closing this PR.

**Pull request closed without merging**
