### PR TITLE
[pix4.c] Added fuzzer

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds a fuzzer that targets the functions in pix4.c that need to be explicitly called in order to be covered.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
Thanks a lot @DanBloomberg

**Comment by AdamKorcz** [comment]
Thank you for the comments. 
Regarding line 94, it did return a pix before, but the name of the variable itself was confusing, so I have changed it.

**Comment by DanBloomberg** [comment]
@AdamKorcz 

3 questions:
(1) Is github testing these fuzzer programs to see if they compile?
(2) How can I compile them?
(3) fuzzing/oss-fuzz-build.sh has a section at the end that copies zip files from $SRC to $OUT.  What's happening here?  I only see 10 of the fuzzers there, but we have 17 fuzzers.

**Comment by AdamKorcz** [comment]
@DanBloomberg 
1: No, Github is not testing these fuzzers. If they fail, we will currently only get notified through oss-fuzz. I did run this fuzzer for 30 minutes with a seed corpus, and it did not break. It would be a great idea to add the fuzzers to the automated checks here on Github, though.
2: I think @stweil setup documentation for running the fuzzers locally. Is that true?
3: We currently make the corpora for 10 of the 17 fuzzers. I will get the corpora added for the new fuzzers over the next days.

**Pull request merged**
