### PR TITLE
Use correct location for CMake files

### PR DESCRIPTION
**Pull request by Shatur95**
CMake files should be located in `${CMAKE_INSTALL_PREFIX}/lib/cmake` instead of `${CMAKE_INSTALL_PREFIX}/cmake`, see [search procedure](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure). I fixed paths in this PR.

### CODE REVIEW

**Comment by Shatur95** [comment]
Noticed another issue not related to this request. When using GNU Autotools, you copy `LeptonicaConfig.cmake`, which includes `LeptonicaTargets.cmake`, which is only generated with CMake. Therefore, if the project was installed using Autotools, then when you search for Leptonica in a CMake project, you will get an error because `LeptonicaTargets.cmake` file does not exist. Are you planning to support both build systems? If yes, is there a way to generate `LeptonicaTargets.cmake` with Autotools? Most Linux distributions use Autotools to build Leptonica.

**Comment by zdenop** [comment]
... and a lot of project are switching to cmake. IMO generating `LeptonicaTargets.cmake` also with autotools make sense, so users are not push to use several building system for one project.

**Comment by Shatur95** [comment]
I would like to help with this, but I am not familiar with GNU Autotools :(

However, this PR can be merged as is because it solves the CMake problem.

**Comment by Shatur95** [comment]
@DanBloomberg, could this PR be merged?

**Comment by DanBloomberg** [comment]
@egorpugin 

Please review. He's putting lib/ into the destination path.

**Comment by egorpugin** [comment]
I'm not familiar with cmake install.
Those lines were contributed by @aleksey-nikolaev in https://github.com/DanBloomberg/leptonica/pull/246

Looking at the initial PR message `search procedure` (https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure) link, proposed paths are used for Unix while Windows uses another convention.
So, this PR might fix unix and break windows systems.

**Comment by Shatur95** [comment]
>  So, this PR might fix unix and break windows systems.

The documentation says that `This is merely a convention, so all (W) and (U) directories are still searched on all platforms.`
So, Windows will work perfectly with `lib/cmake`. And this location is also common for Linux.
Previously, modules were installed directly into the `/cmake` folder, which is bad for Linux. At the moment all distributions just use autotools to install leptonica.

**Comment by egorpugin** [comment]
> At the moment all distributions just use autotools to install leptonica.

Because cmake build was initially windows only.

> The documentation says that This is merely a convention, so all (W) and (U) directories are still searched on all platforms.

I'm merging the PR then.

**Comment by Shatur95** [comment]
Thanks!

**Pull request merged**
