### PR TITLE
Remove config/config.h.in

### PR DESCRIPTION
**Pull request by stweil**
It is generated automatically when running autobuild,
so git should ignore it.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by DanBloomberg** [comment]
Stefan, the travis build failed,  trying to install libwebp-dev.  Is that possibly related to this change?

Also, 2 questions:
(1) how do you get these tests to run?
(2) is the travis build on linux and appveyor on windows?

  -- Dan

**Comment by stweil** [comment]
Yes, the travis checks run on Linux while appveyor checks on windows.

The travis check failed because the connection to the apt server failed. See the message "Service Unavailable" in this extract from the check details:

> The following NEW packages will be installed:
> libwebp-dev libwebpdemux1 libwebpmux1
> 0 upgraded, 3 newly installed, 0 to remove and 233 not upgraded.
> Need to get 225 kB of archives.
> After this operation, 855 kB of additional disk space will be used.
> Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main libwebpdemux1 amd64 0.4.0-4
 > 503  Service Unavailable [IP: 104.197.12.55 80]
> Get:1 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main libwebpmux1 amd64 0.4.0-4 [13.7 kB]
> Get:2 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main libwebp-dev amd64 0.4.0-4 [203 kB]
> Fetched 217 kB in 2s (106 kB/s)
> E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libw/libwebp/libwebpdemux1_0.4.0-4_amd64.deb  503  Service Unavailable [IP: 104.197.12.55 80]

It failed to get `libwebpdemux1_0.4.0-4_amd64.deb`.

It is possible to restart the checks by closing and re-opening the pull request (which I'll do now).

**Comment by DanBloomberg** [comment]
Thanks.  So when I do a commit it runs automatically as well?  How do I check the results?

**Comment by egorpugin** [comment]
Use those green badges at the top of readme https://github.com/DanBloomberg/leptonica#leptonica-library
Click them and you see all results you want.

**Comment by DanBloomberg** [comment]
Thanks Egor -- hidden in plain sight  :-)

**Pull request merged**
