### PR TITLE
Skip gnuplot tests if it is missing PNG support

### PR DESCRIPTION
**Pull request by chewi**
I was getting failures when gnuplot was built without it.

### CODE REVIEW

**Comment by DanBloomberg** [comment]
Thank you James!  I expect to release patch 3 today.

**Comment by egorpugin** [comment]
Not too fast? :)
Later it can become one release per commit.

**Comment by chewi** [comment]
No rush here, I've already patched it on Gentoo.

**Comment by DanBloomberg** [comment]
:-)

Jeff needs the final debian version out this week, for inclusion in the major ubuntu 18.04 release.

Patch 3 should fix a serious bug with webp support on big-endian machines.  If I don't screw up the tarball, we should be done with 1.75.

**Comment by DanBloomberg** [comment]
The patch was no good, so I've essentially reverted it.

We still have an outstanding issue (#307 ) with lossless webp encoding on big-endians.

**Pull request merged**
