### PR TITLE
configure: Support pkg-config

### PR DESCRIPTION
**Pull request by stweil**
The following packages provide compiler and linker flags via pkg-config:

* zlib
* libpng
* libjpeg
* libtiff-4
* libwebp
* libopenjp2

Add the flags from pkg-config to the preprocessor flags.
Add code to include openjpeg.h if LIBJP2K_HEADER was not set.

Packages without a configuration for pkg-config work as before
with the old detection code.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Both AppVeyor builds stopped after an 60 minutes. This seems to be unrelated to my pull request, but to be sure I restart the CI tests by closing and reopening this PR.

**Comment by DanBloomberg** [comment]
Stefan,

The 60 minute timeout was an appveyor problem, not yours.  It happened to me yesterday.

Where does this pull request stand now -- is it safe?

**Comment by stweil** [comment]
I think it is safe. Builds with `cmake` should not be affected at all. I have run tests with `./autobuild && ./configure && make` with Linux native, Windows cross and Windows native builds.

**Comment by DanBloomberg** [comment]
thanks -- fingers crossed  ;-)

**Pull request merged**
