### PR TITLE
fix autotools webpmux

### PR DESCRIPTION
**Pull request by zdenop**
add webpanimio to autotools build

### CODE REVIEW

**Comment by DanBloomberg** [comment]
There were 2 travis (unix) builds.  The first on said it found libwebpmux and it failed trying to compile the new webpanimio.c file.

The second said it didn't find the library, so presumably it compiled the stub file, which doesn't require the library, and it succeeded.

**Comment by zdenop** [comment]
Booth are cmake  builds (e.g. not related to this PR:):
1. is linux build
2. is osx build

**Comment by zdenop** [comment]
travis for OSX  did not have any package for webp (and openjpeg). This is fixed now.
But linux (ubuntu1~14) build  failed (with the same cmake configuration). 
I use openSUSE linux and there it works... Not sure how to find reason why...

**Comment by DanBloomberg** [comment]
so linux with cmake says the library is there but then fails when compiling, so it can't find the webpmux library header file.  I wonder if it can even find the libwebp header files....

@chewi 
if you get a chance, can you look at this, and also the autotools pr  #417 which may need a review.  Thanks!

**Comment by zdenop** [comment]
@egorpugin : Can you help with travis? I tried a lot of things but nothing worked on travis ubuntu cmake build;-)... According [travis log](https://travis-ci.org/DanBloomberg/leptonica/jobs/516876223):  
```
-- Found WEBP library: /usr/lib/x86_64-linux-gnu/libwebp.so
-- WEBP_LIBRARIES: /usr/lib/x86_64-linux-gnu/libwebp.so;/usr/lib/x86_64-linux-gnu/libwebpmux.so
-- WEBP_INCLUDE_DIRS: /usr/include
```
So libraries are found and header files too. But build failed:
```
[ 23%] Building C object src/CMakeFiles/leptonica.dir/webpanimio.c.o
cd /home/travis/build/DanBloomberg/leptonica/build/src && /usr/bin/gcc -DHAVE_CONFIG_H -DLIBLEPT_EXPORTS -Dleptonica_EXPORTS -I/home/travis/build/DanBloomberg/leptonica/src -I/home/travis/build/DanBloomberg/leptonica/build/src -I/usr/local/include -I/usr/include/x86_64-linux-gnu  -fPIC   -o CMakeFiles/leptonica.dir/webpanimio.c.o   -c /home/travis/build/DanBloomberg/leptonica/src/webpanimio.c
/home/travis/build/DanBloomberg/leptonica/src/webpanimio.c: In function ‘pixaWriteMemWebPAnim’:
/home/travis/build/DanBloomberg/leptonica/src/webpanimio.c:180:1: error: unknown type name ‘WebPAnimEncoder’
 WebPAnimEncoder        *enc;
 ^
/home/travis/build/DanBloomberg/leptonica/src/webpanimio.c:181:1: error: unknown type name ‘WebPAnimEncoderOptions’
 WebPAnimEncoderOptions  enc_options;
 ^
/home/travis/build/DanBloomberg/leptonica/src/webpanimio.c:210:9: warning: assignment makes pointer from integer without a cast [enabled by default]
     enc = WebPAnimEncoderNew(w, h, &enc_options);
         ^
make[2]: *** [src/CMakeFiles/leptonica.dir/webpanimio.c.o] Error 1
```
So include paths should be ok, but for some reason  [webp/mux.h](https://chromium.googlesource.com/webm/libwebp/+/master/src/webp/mux.h) is not included...  Even I tried use [-DHAVE_LIBWEBP_ANIM=1](https://github.com/DanBloomberg/leptonica/pull/417/commits/4ff03b913a0cd8b8197bfc4de5fbee4407b763e1)

[travis OSX cmake build](https://travis-ci.org/DanBloomberg/leptonica/jobs/516885263) works, also my home linux (openSUSE) cmake build.

**Comment by egorpugin** [comment]
Maybe there's an old webpmux? (ubuntu 14.04)
Try to set `dist: xenial` for ubuntu 16.04.

**Comment by egorpugin** [comment]
Not sure then. Headers are visible. Maybe error in code?

**Comment by zdenop** [comment]
Also xenial  has webp 0.4.4 - I try to use the latest release of webp 1.0.2. Lets see what happens...

**Comment by zdenop** [comment]
@egorpugin : Thanks! problem is with old version of webp in Ubuntu: we need to check also version: it should be at least [0.5.0](https://github.com/webmproject/libwebp/releases/tag/v0.5.0)

@DanBloomberg @egorpugin : DO NOT merge this PR. I will close it and made new PR.

**Comment by egorpugin** [comment]
It's fine now. Rebase please and probably set back trusty distro?

**Comment by egorpugin** [comment]
> DO NOT merge this PR. I will close it and made new PR.

Ok.

**Pull request closed without merging**
