### PR TITLE
pnmio.c: avoid fseek()

### PR DESCRIPTION
**Pull request by giuliolunati**
The goal is to make it possible
to read a PNM/PAM image from stdin (netpbm-like),
which is currently not working: see issue #580.

The reason is the use of fseek(fp, -1, SEEK_CUR)
to "go back" after a fgetc(),
which doesn't work for stdin,
so it has been replaced through fscanf().

### CODE REVIEW

**Comment by giuliolunati** [comment]
This could close #580

**Comment by DanBloomberg** [comment]
Very elegant solution to the problem!
I am letting it build..
Verified it works on your test file using your patch.
Will do some other checks tomorrow and then merge.
Thank you very much for this.

Dan

**Comment by giuliolunati** [comment]
And thank you very much to you for Leptonica!
I learned a lot from your code.
Now I'm working on a CLI utility for fixing my scanned docs.

**Comment by DanBloomberg** [comment]
Is your name Giulio Lunati, by any chance  ;-)
I want to acknowledge you for your improvements to pnm reading.

Dan

**Comment by giuliolunati** [comment]
Yes Dan, I'm Giulio Lunati (Pavia, Italy)
Thank you :-)

**Comment by DanBloomberg** [comment]
Thank you again.
I will put some comments in line with the code.

**Pull request merged**
