### PR TITLE
Cmake improve

### PR DESCRIPTION
**Pull request by zdenop**

### CODE REVIEW

**Comment by zdenop** [comment]
Please do not merge this PR yet - openjpeg is causing problem for building tesseract (because of missing path to library)

**Comment by DanBloomberg** [comment]
Thanks.  I'll wait for your OK.

Dan

**Comment by zdenop** [comment]
Now it is ready for merge: my test shows it is working from openjpeg-2.1.1 to the latest git clone (2.5.0)

**Comment by DanBloomberg** [comment]
Great.  Thank you for doing this.  It's too bad that openjpeg puts the include files in a release specific subdirectory.

**Comment by VVD** [comment]
> Great. Thank you for doing this. It's too bad that openjpeg puts the include files in a release specific subdirectory.

Possibility to install different versions (branches) on one system.

**Pull request merged**
