### PR TITLE
Fix remaining warnings from lgtm

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by DanBloomberg** [comment]
thanks!  Nice not to have lgtm nagging us    :-)

**Comment by stweil** [comment]
I'm sorry, but I only fixed the three warnings. lgtm will still complain about one remaining issue which it considers to be an error, not a warning: the potentially dangerous function `gmtime`.

**Comment by DanBloomberg** [comment]
Even better to have 1 "alert", to remind us that software can never be perfect  :-)

I believe that gmtime can only make an error in a multi-threaded situation.

**Comment by stweil** [comment]
Leptonica can be used in multi-threaded applications, so I decided to fix that one, too.

**Pull request merged**
