### PR TITLE
cmake install configuration

### LINKED ISSUE #117: Add install targets to cmake

### PR DESCRIPTION
**Pull request by aleksey-nikolaev**
I don`t know what exactly programs need to be installed, so I took the option from Makefile.am.
Probably fix #117

### CODE REVIEW

**Comment by DanBloomberg** [comment]
Aleksey, thanks!

For some reason, I thought we decided not to install the generated endianness.h, and it was put into .gitignore.

I'm not fluent with cmake, so I'll let Egor Pugin review this and handle the merge.

**Comment by aleksey-nikolaev** [comment]
Hi!
Yes, endianness.h - is cmake generated file, but I have to add this file to the install due to alltypes.h is depending on.
And I can't remove this dependence nor exclude alltypes.h because the tesseract used alltypes.h

**Comment by chewi** [comment]
endianness.h should be installed.

**Comment by DanBloomberg** [comment]
and removed from .gitignore?

**Comment by chewi** [comment]
No, it's generated so you don't want it committed.

**Comment by DanBloomberg** [comment]
installed but not committed??

Does anything need to be changed?  If so, can you please submit a patch?

**Comment by egorpugin** [comment]
Stop it, please. Everything is fine before and after the merge.
No additional changes are required.

**Pull request merged**
