### PR TITLE
Remove C99 style inline declaration

### PR DESCRIPTION
**Pull request by chris-liddell**
Trivial patch.

### CODE REVIEW

**Comment by stweil** [comment]
That code was added in commit df0fe14f8.

I am curious: are there still build environments which don't accept such inline declarations (which I personally like because they require less code lines and are easier to review)?

If we want to avoid inline declarations, I suggest to update the commit and format the declaration like most others in the Leptonica code (left aligned, empty line after declaration).

**Comment by stweil** [comment]
C99 is now more that 20 years old. "C99 is substantially completely supported as of GCC 4.5". gcc 4.5.0 was released April 14, 2010.  I think that compilers are no longer a reason to avoid them.

**Comment by DanBloomberg** [comment]
You are probably correct, and perhaps we should not sweat the inline declarations going forward.

Perhaps more important than the date that gcc first supported C99 is the reluctant acceptance of C99 by Microsoft 

This is from Wikipedia:
```
Most C compilers provide support for at least some of the features introduced in C99.

Historically, [Microsoft](https://en.wikipedia.org/wiki/Microsoft) has been slow to implement new C features in their [Visual C++](https://en.wikipedia.org/wiki/Visual_C%2B%2B) tools, instead focusing mainly on supporting developments in the C++ standards.[[13]](https://en.wikipedia.org/wiki/C99#cite_note-13) However, with the introduction of Visual C++ 2013 Microsoft implemented a limited subset of C99, which was expanded in Visual C++ 2015.[[14]](https://en.wikipedia.org/wiki/C99#cite_note-vs2015_new-14)
```

**Comment by chris-liddell** [comment]
Oops, sorry, I did miss the other requirements....

This came up because we (Ghostscript) still get used on some older, obscure platforms (like a Unix emulation environment running on IBM s/390 mainframes) where gcc is not the de facto standard. IBM's C compiler lags behind and, due to the astronomical upgrade costs, their customers lag even further behind. Which is why Ghostscript still avoids C99 and later constructs.

**Review by stweil — APPROVED** [review]
Looks good now, thank you!

**Comment by DanBloomberg** [comment]
Thank you for explaining.  Those legacy issues are always annoying.
We'll keep avoiding inline declarations.

**Pull request merged**
