### PR TITLE
CMake: Use BUILD_SHARED_LIBRARIES and get rid of LIBRARY_TYPE

### PR DESCRIPTION
**Pull request by 1480c1**
Still retain `STATIC` for backwards compatibility, but just map `!STATIC` to setting [`BUILD_SHARED_LIBRARIES`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html)

If wanted, I can reverse the mapping, but I don't see a reason to do that since [`BUILD_SHARED_LIBRARIES`](https://cmake.org/cmake/help/v2.8.11/cmake.html#variable:BUILD_SHARED_LIBS) exists even on 2.8.11

### CODE REVIEW

**Comment by DanBloomberg** [comment]
@egorpugin 

please eval

**Comment by egorpugin** [comment]
@1480c1 thank you.
Could you please remove STATIC completely from cmake files? And option()s you've introduced too.
And use BUILD_SHARED_LIBRARIES instead.

**Comment by 1480c1** [comment]
> @1480c1 thank you.
> Could you please remove STATIC completely from cmake files? And option()s you've introduced too.
> And use BUILD_SHARED_LIBRARIES instead.

Sure, I mainly kept `STATIC` since that was already there

**Comment by egorpugin** [comment]
There are also two STATIC checks in src/cmakelists and prog/cmakelists.

**Comment by egorpugin** [comment]
Thanks!

**Comment by 1480c1** [comment]
Thank you

**Pull request merged**
