### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/DanBloomberg/leptonica/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/DanBloomberg/leptonica).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by DanBloomberg** [comment]
This looks like a useful service.  I'll check out a few of the alerts and get back to you in a few days.

**Comment by xcorail** [comment]
Don't hesitate to ask questions as you go.

**Comment by DanBloomberg** [comment]
I have modified code in response to most of the 32 alerts that lgtm has indicated.

I assume lgtm is doing a static analysis of the code.  How often is this done, and how does it compare with Coverity Scan, which also runs on this library?

**Comment by xcorail** [comment]
Hi @DanBloomberg 
Happy to hear that it was useful to you!

LGTM indeed runs an analysis of the code. The particularity is that we are able to make deeper semantic analysis, thanks to our technology combining academic work on both DB and optimisations.
I guess you would be in better position than me to compare Coverity and LGTM, given your knowledge and the particularity of your code. I mean, you would be able to check if LGTM finds alerts that Coverity doesn't, and very importantly, without slowing you down with false positives.

LGTM analyses all commits on public repos. Priority is given to 
1. pull requests  
2. HEAD commits of all projects
3. all commits (it goes back in time)

Writing this I realise that I didn't mention the PR integration ... You can easily activate the PR integration [here](https://lgtm.com/projects/g/DanBloomberg/leptonica/ci/), so that LGTM reports directly within the pull request any new alert.

Cheers

**Comment by DanBloomberg** [comment]
Maybe change the text in the two 'badges' to:
  LGTM Code Quality
  LGTM Alerts

**Comment by xcorail** [comment]
Because we're using Shields.io, these badges are entirely customizable. You can, if you wish, change their style, colors and label. Instructions are available on [their website](https://shields.io/#/).
And we hope that with time the [tarsier](https://en.wikipedia.org/wiki/Tarsier) in the badge will be associated easily with LGTM :-)

**Comment by DanBloomberg** [comment]
ok, let's give it a try  :-)

**Comment by xcorail** [comment]
@DanBloomberg 
Re-reading our previous exchanges, I see that I failed to answer your question "how often is this done?". 
* Pull Requests are analysed immediately, if you activate the integration
* Commits are pulled once a day

**Pull request merged**
