### PR TITLE
Avoid brokenness with custom pix memory handlers.

### PR DESCRIPTION
**Pull request by robinwatts**
setPixMemoryHandler allows custom malloc/free handlers to be
set. Then the code goes and uses calloc to get a block that
it later feeds to the custom free handler. Obviously, this
leads to crashes.

### CODE REVIEW

**Comment by robinwatts** [comment]
I need to find some way to solve the general case (i.e. ALL allocations, on all platforms, not just the pix ones), but at least with this commit the defined interface won't cause crashes.

**Comment by DanBloomberg** [comment]
Thank you for submitting this.

It was never intended to do memory management on anything besides images.
The reason is that they can be very large, and an application may be improved by not freeing and reallocating many if they're the same size, for example.

Allocators for small objects are very efficient, and memory fragmentation isn't usually an issue.

**Comment by DanBloomberg** [comment]
I don't understand what you did to get a crash.
The custom allocator is only used for the data array in the pix.
All other data arrays, and all structs like the Pix are allocated with the system malloc and alloc.

Your PR shows in lines 555 and 667 the use of the custom allocator to calloc and free the Pix struct itself, not the raster data.    Why was it necessary to do that?

**Comment by robinwatts** [comment]
On Monday, I had absolutely convinced myself that this was required. I had crashes in my test code to indicate it. First I had a crash in the free which lead to my "fix", which lead (obviously) to problems with the calloc.

Then yesterday, I found a bug in my code with interaction with garbage collection.

Looking at the changes again now, especially in light of your comments, I can't see why these changes could be necessary. I can only assume that I misdiagnosed the initial problem I found given a crash on free caused by the gc issue.

So, sorry, apologies for having wasted your time!

**Pull request closed without merging**
