### PR TITLE
Use the VERSION argument of the project call

### PR DESCRIPTION
**Pull request by autoantwort**

### CODE REVIEW

**Comment by zdenop** [comment]
```sh
>git fetch upstream pull/665/head:pr665
>git checkout pr665
>cmake -Bbuild.662 -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=%INSTALL_DIR% -DBUILD_PROG=OFF -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON
CMake Error at CMakeLists.txt:42 (project):
  project with VERSION, DESCRIPTION or HOMEPAGE_URL must use LANGUAGES before
  language names.
```

```sh
>cmake --version
cmake version 3.25.2
```

**Comment by autoantwort** [comment]
Fixed it :)

**Comment by autoantwort** [comment]
Fixed it :)

**Comment by DanBloomberg** [comment]
@zdenop 

There are a large number of naming changes in this PR.
I'll run the workflows.

**Comment by autoantwort** [comment]
The fuzzing pipeline failure is afaiu unrelated to this PR

**Comment by zdenop** [comment]
@DanBloomberg : I would suggest merging this.
I do not see a problem with it, but it could affect external projects using leptonica, I am afraid without merging to master they will not test it.

**Comment by DanBloomberg** [comment]
@zdenop :  merged

**Pull request merged**
