### PR TITLE
Fix oss-fuzz build failure

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49777
Fixes: https://github.com/google/oss-fuzz/issues/8152

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
CC @AdamKorcz

**Review by stweil — APPROVED** [review]
Thank you for fixing this oss-fuzz build issue.

**Comment by DavidKorczynski** [comment]
The CIFuzz failure should be due to a limitation in CIFuzz rather than this fix. When I substitute https://github.com/google/oss-fuzz/blob/c1bcbc2c54d0d28de5c0556ad1a0b817ea0ae291/projects/leptonica/Dockerfile#L20 for `RUN git clone https://github.com/DavidKorczynski/leptonica && cd leptonica && git checkout leptonica-ossfix` and run the OSS-Fuzz `check_build` then I get `Check build passed.` and the build succeeds.

**Comment by DanBloomberg** [comment]
Thank you David for maintaining the leptonica fuzz scripts and fixing this.  I'll merge and we'll see if CIFuzz is fixed.

**Pull request merged**
