### PR TITLE
giflib version check and other configure improvements

### PR DESCRIPTION
**Pull request by chewi**

### CODE REVIEW

**Comment by DanBloomberg** [comment]
Really nice job!!!

**Comment by DanBloomberg** [comment]
This tests out perfectly.

there is one puzzle.  config_auto.h has an extra entry for the openjpeg library, which is commented out.  The line for LIBJP2K is the only one that is meaningful.  The LIBOPENJP2 token isn't referenced in the library, so it doesn't do any harm, but I don't know where it came from.

I couldn't attach the file, but here are the relevant lines:


/* Define to 1 if you have libopenjp2. */
#define HAVE_LIBJP2K 1

...

/* Define to 1 if you have the `openjp2' library (-lopenjp2). */
/* #undef HAVE_LIBOPENJP2 */

**Comment by DanBloomberg** [comment]
I can guess that it was manufactured by automake based on the name of the library, which is libopenjp2.

In any event, it does no harm, so if it would be hard to get rid of, don't bother.

**Comment by chewi** [comment]
Fixed that in #306.

**Pull request merged**
